# Generated by Django 4.2.6 on 2023-10-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asig',
            new_name='assignment',
        ),
    ]
