# Generated by Django 4.2.6 on 2023-10-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0004_materia_profesor_alter_categoria_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
