# Generated by Django 4.2.6 on 2023-10-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0005_alter_profesor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auxiliar',
                'verbose_name_plural': 'Auxiliares',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Auxiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.auxiliar'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Dias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.dia'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.precio'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.salon'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.seccion'),
        ),
    ]
