# Generated by Django 4.2.6 on 2023-10-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0006_auxiliar_dia_precio_salon_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Auxiliar',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Dias',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Precio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Salon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Seccion',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Auxiliar',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
