# Generated by Django 4.2.6 on 2023-10-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0008_seccion_alter_categoria_seccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
