# Generated by Django 4.2.6 on 2023-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_remove_curso_inscritos_curso_cupo_curso_descripcion_and_more'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cursos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='inscritos', to='cursos.curso'),
        ),
    ]
