# Generated by Django 4.2.6 on 2023-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nombre',
            new_name='Fecha',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='DPI',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Usuario',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Telefono',
            field=models.CharField(default='', max_length=100),
        ),
    ]
