# Generated by Django 4.2.6 on 2023-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('estudiante', '0002_customuser_cursos_inscritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dpi',
            new_name='DPI',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_nacimiento',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telefono',
            new_name='Telefono',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
