# Generated by Django 4.2.6 on 2023-10-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_customuser_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
