# Generated by Django 4.2.6 on 2023-10-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_rename_dpi_customuser_dpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='DPI',
        ),
    ]
