# Generated by Django 4.2.6 on 2023-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_remove_customuser_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dpi',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
