# Generated by Django 4.2.6 on 2023-10-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_customuser_dpi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dpi',
            new_name='DPI',
        ),
    ]
