# Generated by Django 4.2.6 on 2023-10-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cursos',
            new_name='Curso',
        ),
    ]
