# Generated by Django 4.2.6 on 2023-10-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_cursos_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
    ]
