# Generated by Django 4.2.6 on 2023-10-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_materia_profesor_alter_curso_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Docente',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
