# Generated by Django 4.2.6 on 2023-10-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_materia_profesor_alter_curso_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='Dias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.dia'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.seccion'),
        ),
    ]
