# Generated by Django 4.2.6 on 2023-10-14 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_dia_seccion_alter_curso_dias_alter_curso_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auxiliar',
                'verbose_name_plural': 'Auxiliar',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='Salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.salon'),
        ),
    ]
