# Generated by Django 4.2.6 on 2023-10-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_rename_curso_curso_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Nombre',
            new_name='Curso',
        ),
    ]
