# Generated by Django 4.2.5 on 2023-10-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_rename_nombre_curso_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Dias',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Salon',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Seccion',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
