# Generated by Django 4.2.5 on 2023-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_remove_curso_dias_remove_curso_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Auxiliar',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Docente',
        ),
        migrations.AlterField(
            model_name='curso',
            name='Curso',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Edificio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Precio',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Auxiliar',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
