# Generated by Django 4.2.5 on 2023-10-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_remove_curso_auxiliar_remove_curso_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Curso',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
