# Generated by Django 4.2.6 on 2023-10-20 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0015_alter_curso_curso_alter_curso_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Curso',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Edificio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Precio',
        ),
        migrations.AddField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
