# Generated by Django 4.2.6 on 2023-10-24 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0019_alter_curso_estudiantes_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cupo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
